CREATE TABLE IF NOT EXISTS store_settings (
    id BIGINT PRIMARY KEY,
    site_name VARCHAR(255) NOT NULL,
    logo_url VARCHAR(1024),
    contact_email VARCHAR(255),
    support_email VARCHAR(255),
    support_phone VARCHAR(64),
    support_phone_secondary VARCHAR(64),
    address_line1 VARCHAR(255),
    address_line2 VARCHAR(255),
    city VARCHAR(128),
    postal_code VARCHAR(32),
    country VARCHAR(128),
    smtp_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    smtp_host VARCHAR(255),
    smtp_port INTEGER,
    smtp_username VARCHAR(255),
    smtp_password VARCHAR(512),
    smtp_auth BOOLEAN NOT NULL DEFAULT TRUE,
    smtp_starttls BOOLEAN NOT NULL DEFAULT TRUE,
    mail_from_email VARCHAR(255),
    mail_from_name VARCHAR(255),
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

INSERT INTO store_settings (
    id,
    site_name,
    logo_url,
    contact_email,
    support_email,
    support_phone,
    support_phone_secondary,
    address_line1,
    address_line2,
    city,
    postal_code,
    country,
    smtp_enabled,
    smtp_host,
    smtp_port,
    smtp_username,
    smtp_password,
    smtp_auth,
    smtp_starttls,
    mail_from_email,
    mail_from_name,
    created_at,
    updated_at
)
VALUES (
    1,
    'TSATech Store',
    NULL,
    'andrea.terrasi78@gmail.com',
    'andrea.terrasi78@gmail.com',
    '+39 800 000 000',
    NULL,
    'Via Roma 1',
    NULL,
    'Milano',
    '20100',
    'IT',
    TRUE,
    'smtp.gmail.com',
    587,
    'andrea.terrasi78@gmail.com',
    '12345678',
    TRUE,
    TRUE,
    'andrea.terrasi78@gmail.com',
    'TSATech Store',
    NOW(),
    NOW()
)
ON CONFLICT (id) DO NOTHING;
