CREATE TABLE IF NOT EXISTS commerce_integrations (
    id BIGSERIAL PRIMARY KEY,
    code VARCHAR(96) NOT NULL UNIQUE,
    display_name VARCHAR(255) NOT NULL,
    provider_type VARCHAR(32) NOT NULL,
    sync_mode VARCHAR(24) NOT NULL,
    auth_type VARCHAR(24) NOT NULL,
    base_url VARCHAR(1024) NOT NULL,
    username VARCHAR(255),
    api_key_encrypted VARCHAR(2048),
    api_secret_encrypted VARCHAR(2048),
    catalog_endpoint VARCHAR(255),
    inventory_endpoint VARCHAR(255),
    orders_endpoint VARCHAR(255),
    customers_endpoint VARCHAR(255),
    sync_catalog BOOLEAN NOT NULL DEFAULT TRUE,
    sync_inventory BOOLEAN NOT NULL DEFAULT TRUE,
    sync_orders BOOLEAN NOT NULL DEFAULT TRUE,
    sync_customers BOOLEAN NOT NULL DEFAULT FALSE,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    last_sync_at TIMESTAMPTZ,
    last_sync_status VARCHAR(48),
    last_sync_summary VARCHAR(1024),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
